/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SettingsImport } from './routes/settings'
import { Route as DashboardImport } from './routes/dashboard'
import { Route as CocktailsImport } from './routes/cocktails'
import { Route as IndexImport } from './routes/index'
import { Route as CocktailsCocktailIdImport } from './routes/cocktails.$cocktailId'

// Create/Update Routes

const SettingsRoute = SettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRoute,
} as any)

const DashboardRoute = DashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const CocktailsRoute = CocktailsImport.update({
  id: '/cocktails',
  path: '/cocktails',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const CocktailsCocktailIdRoute = CocktailsCocktailIdImport.update({
  id: '/$cocktailId',
  path: '/$cocktailId',
  getParentRoute: () => CocktailsRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/cocktails': {
      id: '/cocktails'
      path: '/cocktails'
      fullPath: '/cocktails'
      preLoaderRoute: typeof CocktailsImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsImport
      parentRoute: typeof rootRoute
    }
    '/cocktails/$cocktailId': {
      id: '/cocktails/$cocktailId'
      path: '/$cocktailId'
      fullPath: '/cocktails/$cocktailId'
      preLoaderRoute: typeof CocktailsCocktailIdImport
      parentRoute: typeof CocktailsImport
    }
  }
}

// Create and export the route tree

interface CocktailsRouteChildren {
  CocktailsCocktailIdRoute: typeof CocktailsCocktailIdRoute
}

const CocktailsRouteChildren: CocktailsRouteChildren = {
  CocktailsCocktailIdRoute: CocktailsCocktailIdRoute,
}

const CocktailsRouteWithChildren = CocktailsRoute._addFileChildren(
  CocktailsRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cocktails': typeof CocktailsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/settings': typeof SettingsRoute
  '/cocktails/$cocktailId': typeof CocktailsCocktailIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cocktails': typeof CocktailsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/settings': typeof SettingsRoute
  '/cocktails/$cocktailId': typeof CocktailsCocktailIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/cocktails': typeof CocktailsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/settings': typeof SettingsRoute
  '/cocktails/$cocktailId': typeof CocktailsCocktailIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cocktails'
    | '/dashboard'
    | '/settings'
    | '/cocktails/$cocktailId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cocktails' | '/dashboard' | '/settings' | '/cocktails/$cocktailId'
  id:
    | '__root__'
    | '/'
    | '/cocktails'
    | '/dashboard'
    | '/settings'
    | '/cocktails/$cocktailId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CocktailsRoute: typeof CocktailsRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  SettingsRoute: typeof SettingsRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CocktailsRoute: CocktailsRouteWithChildren,
  DashboardRoute: DashboardRoute,
  SettingsRoute: SettingsRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/cocktails",
        "/dashboard",
        "/settings"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/cocktails": {
      "filePath": "cocktails.tsx",
      "children": [
        "/cocktails/$cocktailId"
      ]
    },
    "/dashboard": {
      "filePath": "dashboard.tsx"
    },
    "/settings": {
      "filePath": "settings.tsx"
    },
    "/cocktails/$cocktailId": {
      "filePath": "cocktails.$cocktailId.tsx",
      "parent": "/cocktails"
    }
  }
}
ROUTE_MANIFEST_END */
